<?php
$res = array(
'Insert_FH' => 'Add',
'Update_FH' => 'Update',
'Record_FH' => 'Record',
'Insert_FB' => '&#xf044',
'Update_FB' => '&#xf044',
'Delete_FB' => '&#xf2ed',
'Cancel_FB' => '&#xf2ea',
'Insert as new_FB' => 'Add as new',
'Select one...' => 'Select one...',
'Are you sure?' => 'Are you sure?',
'Are you sure cancel?' => 'Are you sure you want to cancel? Any changes will be lost',
'Filter' => 'Filter',
'Show' => 'Show',
'all' => 'all',
'records' => 'records',
'Reset filter' => 'Reset filter',
'Show filter' => 'Show filter',
'Order' => 'Order',
'save' => 'Save',
'None' => 'None',
'The table is empty or the filter you\'ve selected is too restrictive.' => 'No data, the filter returned no results.',
'edit_one' => '<i class="fas fa-edit fa-2x"></i>',
'delete_one' => '<i class="fas fa-trash-alt fa-2x"></i>',
'edit_all' => '<i class="fas fa-clipboard-list fa-3x"></i>',
'delete_all' => '<i class="fas fa-trash-alt fa-3x"></i>',
'add new' => '<i class="fas fa-file-plus fa-3x"></i>',
'ARE_YOU_SURE_MOVE' => 'You changed the order of some records and did not save the changes. If you continue, the changes will be lost.',
'ARE_YOU_SURE_DELETE' => 'Are you sure you want to delete? It cannot be undone.',
'PLEASE_SELECT_RECORD' => 'Please select a record.',
'to' => 'to',
'of' => 'of',
'First' => 'First',
'Previous' => 'Previous',
'Next' => 'Next',
'Last' => 'Last',
);
?>
